/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsNewRouteImport } from './routes/patients/new'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients/$patientId/index'
import { Route as PatientsPatientIdEditRouteImport } from './routes/patients/$patientId/edit'
import { Route as PatientsPatientIdNotesIndexRouteImport } from './routes/patients/$patientId/notes/index'
import { Route as PatientsPatientIdNotesNoteIdIndexRouteImport } from './routes/patients/$patientId/notes/$noteId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/patients/$patientId/',
  path: '/patients/$patientId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdEditRoute = PatientsPatientIdEditRouteImport.update({
  id: '/patients/$patientId/edit',
  path: '/patients/$patientId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdNotesIndexRoute =
  PatientsPatientIdNotesIndexRouteImport.update({
    id: '/patients/$patientId/notes/',
    path: '/patients/$patientId/notes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientsPatientIdNotesNoteIdIndexRoute =
  PatientsPatientIdNotesNoteIdIndexRouteImport.update({
    id: '/patients/$patientId/notes/$noteId/',
    path: '/patients/$patientId/notes/$noteId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients': typeof PatientsIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/notes': typeof PatientsPatientIdNotesIndexRoute
  '/patients/$patientId/notes/$noteId': typeof PatientsPatientIdNotesNoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients': typeof PatientsIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/notes': typeof PatientsPatientIdNotesIndexRoute
  '/patients/$patientId/notes/$noteId': typeof PatientsPatientIdNotesNoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/patients/new': typeof PatientsNewRoute
  '/patients/': typeof PatientsIndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/notes/': typeof PatientsPatientIdNotesIndexRoute
  '/patients/$patientId/notes/$noteId/': typeof PatientsPatientIdNotesNoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/patients/new'
    | '/patients'
    | '/patients/$patientId/edit'
    | '/patients/$patientId'
    | '/patients/$patientId/notes'
    | '/patients/$patientId/notes/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/patients/new'
    | '/patients'
    | '/patients/$patientId/edit'
    | '/patients/$patientId'
    | '/patients/$patientId/notes'
    | '/patients/$patientId/notes/$noteId'
  id:
    | '__root__'
    | '/'
    | '/api/$'
    | '/patients/new'
    | '/patients/'
    | '/patients/$patientId/edit'
    | '/patients/$patientId/'
    | '/patients/$patientId/notes/'
    | '/patients/$patientId/notes/$noteId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  PatientsNewRoute: typeof PatientsNewRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  PatientsPatientIdEditRoute: typeof PatientsPatientIdEditRoute
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
  PatientsPatientIdNotesIndexRoute: typeof PatientsPatientIdNotesIndexRoute
  PatientsPatientIdNotesNoteIdIndexRoute: typeof PatientsPatientIdNotesNoteIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/edit': {
      id: '/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof PatientsPatientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/notes/': {
      id: '/patients/$patientId/notes/'
      path: '/patients/$patientId/notes'
      fullPath: '/patients/$patientId/notes'
      preLoaderRoute: typeof PatientsPatientIdNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/notes/$noteId/': {
      id: '/patients/$patientId/notes/$noteId/'
      path: '/patients/$patientId/notes/$noteId'
      fullPath: '/patients/$patientId/notes/$noteId'
      preLoaderRoute: typeof PatientsPatientIdNotesNoteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  PatientsNewRoute: PatientsNewRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  PatientsPatientIdEditRoute: PatientsPatientIdEditRoute,
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
  PatientsPatientIdNotesIndexRoute: PatientsPatientIdNotesIndexRoute,
  PatientsPatientIdNotesNoteIdIndexRoute:
    PatientsPatientIdNotesNoteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
